services:
  web:
    image: mmeissen/fetap-server:latest
    restart: always
  
  nginx:
    image: mmeissen/fetap-nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=fetap.net
      - NGINX_PORT=80
    volumes:
      - certbot-www:/var/www/certbot/:ro
      - certbot-conf:/etc/nginx/ssl/:ro

  asterisk:
    image: mmeissen/fetap-asterisk:latest
    restart: always
    ports:
      - "5060:5060/udp"
      - "10000-20000:10000-20000/udp"

  certbot:
    image: mmeissen/fetap-certbot:latest
    container_name: certbot_1
    volumes:
      - certbot-www:/var/www/certbot/:rw
      - certbot-conf:/etc/letsencrypt/:rw

  certbot_restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 43200; docker restart certbot_1; done"]
    restart: always

volumes:
  certbot-www:
  certbot-conf:
