services:
  web:
    image: mmeissen/fetap-server:latest
    restart: always
  
  nginx:
    image: mmeissen/fetap-nginx:latest
    restart: always
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=fetap.net
      - NGINX_PORT=80
