name: Cross compile PJSUA for ARM64

on:
  push:
    paths:
      - .github/workflows/compile-pjsua.yml

env:
  PJSUA_VERSION: 2.14.1

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
      - name: Install cross compiler and build utils
        run: |
          apt-get update
          apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            cmake \
            build-essential \
            wget \
            swig \
            python3-dev \
            python3-pip

      - name: Download source release of PJSUA/PJSIP
        run: |
          wget --no-verbose https://github.com/pjsip/pjproject/archive/refs/tags/${PJSUA_VERSION}.tar.gz
          tar -xvf ${PJSUA_VERSION}.tar.gz
          mv pjproject-${PJSUA_VERSION} pjproject

      - name: Build PJProject
        run: |
          cd pjproject
          ./configure CFLAGS="-fPIC"
          make dep
          make
      
      - name: Buld Python SWIG Module
        run: |
          cd pjproject/pjsip-apps/src/swig/python
          echo "all:" >> Makefile
          echo "	python setup.py bdist_wheel" >> Makefile
          make
          find .

    #   - name: Upload binary
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: hello
    #       path: build/hello