name: Cross compile PJSUA for ARM64

on:
  push:
    paths:
      - .github/workflows/compile-pjsua.yml

env:
  PJSUA_VERSION: 2.14.1

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
      - name: Install cross compiler and build utils
        run: |
          apt-get update
          apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            cmake \
            build-essential \
            wget \
            swig \
            python3-dev \
            python3-pip

      - name: Download source release of PJSUA/PJSIP
        run: |
          wget --no-verbose https://github.com/pjsip/pjproject/archive/refs/tags/${PJSUA_VERSION}.tar.gz
          tar -xvf ${PJSUA_VERSION}.tar.gz
          mv pjproject-${PJSUA_VERSION} pjproject

      - name: Build PJProject
        run: |
          cd pjproject
          ./configure CFLAGS="-fPIC"
          make dep
          make
      
      - name: Buld Python SWIG Module
        run: |
          cd pjproject/pjsip-apps/src/swig/python
          make
          mkdir package
          make install
          mv $(python3 -m site --user-site)/pjsua2-2.14.1-py3.11-linux-x86_64.egg pjsua2-2.14.1-py3.11-linux-x86_64.egg
          rm -rf pjsua2-2.14.1-py3.11-linux-x86_64.egg/__pycache__
          tar -czvf pjsua2.tar.gz pjsua2-2.14.1-py3.11-linux-x86_64.egg

      - name: Upload Wheel
        uses: actions/upload-artifact@v3
        with:
          name: pjsua2
          path: pjproject/pjsip-apps/src/swig/python/pjsua2.tar.gz