name: Build Server Docker Image

on: [push]
jobs:
  build:
    runs-on: [self-hosted, arm64]
    name: Build Docker image and push to Docker Hub
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./server/fetap-server
          file: ./server/fetap-server/Dockerfile
          push: true
          tags: mmeissen/fetap-server:latest,mmeissen/fetap-server:${{ github.sha }}

  deploy_server:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: fetap.net
          username: momo
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: server/docker-compose-prod.yml
          target: /home/momo/usb2/server
          rm: true
          strip_components: 1

      - name: Deploy via ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: fetap.net
          username: momo
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/momo/usb2/server
            docker compose -f docker-compose-prod.yml down
            docker compose up -d --pull always --remove-orphans
            docker system prune --all --force



