name: Build Server Docker Image

on: [push]
jobs:
  build:
    runs-on: [self-hosted, arm64]
    name: Build Docker image and push to Docker Hub
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./fetap-server
          file: ./fetap-server/Dockerfile
          push: true
          tags: https://hub.docker.com/u/mmeissen/fetap-server:latest,https://hub.docker.com/u/mmeissen/fetap-server:${{ github.sha }}

