name: Deploy Server

on: 
  push:
    branches: ["main"]

jobs:
  build_device_docker_images:
    strategy:
      matrix:
        service-name:
          - fetap-core
    runs-on: [self-hosted, arm64]
    name: Build and push ${{ matrix.service-name }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check if files changed
        uses: marceloprado/has-changed-path@v1.0.1
        id: service-changed
        with:
          paths: device/${{ matrix.service-name }}

  build_server_docker_images:
    strategy:
      matrix:
        service-name:
          - fetap-nginx
          - fetap-server
    runs-on: [self-hosted, arm64]
    name: Build and push ${{ matrix.service-name }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check if files changed
        uses: marceloprado/has-changed-path@v1.0.1
        id: service-changed
        with:
          paths: server/${{ matrix.service-name }}

      - name: Log in to Docker Hub
        if: steps.service-changed.outputs.changed == 'true'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.service-changed.outputs.changed == 'true'
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./server/${{ matrix.service-name }}
          file: ./server/${{ matrix.service-name }}/Dockerfile
          push: true
          tags: mmeissen/${{ matrix.service-name }}:latest,mmeissen/${{ matrix.service-name }}:${{ github.sha }}

  deploy_server:
    needs: [build_server_docker_images]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check if files changed
        uses: marceloprado/has-changed-path@v1.0.1
        id: server-changed
        with:
          paths: server

      - name: Copy docker-compose.yml
        if: steps.server-changed.outputs.changed == 'true'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: fetap.net
          username: momo
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: server/docker-compose-prod.yml
          target: /home/momo/usb2/server
          rm: true
          strip_components: 1

      - name: Deploy via ssh
        if: steps.server-changed.outputs.changed == 'true'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: fetap.net
          username: momo
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/momo/usb2/server
            docker compose -f docker-compose-prod.yml down
            docker compose -f docker-compose-prod.yml up -d --pull always --remove-orphans
            docker system prune --all --force



